<?php

/**
 * PluginaPeopleSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaPeopleSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaPeopleSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaPeopleSlot');
    }
}