<?php

/**
 * aAnchorTitleSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aAnchorTitleSlotTable extends PluginaAnchorTitleSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aAnchorTitleSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aAnchorTitleSlot');
    }
}