<?php

/**
 * aBetterTwitterSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aBetterTwitterSlotTable extends PluginaBetterTwitterSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aBetterTwitterSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aBetterTwitterSlot');
    }
}