<?php

/**
 * aContactSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aContactSlotTable extends PluginaContactSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aContactSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aContactSlot');
    }
}