<?php

/**
 * aEtsySlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aEtsySlotTable extends PluginaEtsySlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aEtsySlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aEtsySlot');
    }
}