<?php

/**
 * aPhotoGridSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aPhotoGridSlotTable extends PluginaPhotoGridSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aPhotoGridSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aPhotoGridSlot');
    }
}