<?php

/**
 * aReusableSlideshowSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aReusableSlideshowSlotTable extends PluginaReusableSlideshowSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aReusableSlideshowSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aReusableSlideshowSlot');
    }
}