<?php

/**
 * betterTwitterSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class betterTwitterSlotTable extends PluginbetterTwitterSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object betterTwitterSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('betterTwitterSlot');
    }
}