<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/03/06 17:50:21
sfConfig::add(array(
  'app_default_culture' => 'fr',
  'app_sf_guard_plugin_routes_register' => false,
  'app_a_editor' => 'ck',
  'app_a_ckEditor_toolbars' => array (
  'Default' => 
  array (
    0 => 
    array (
      0 => 'Maximize',
      1 => 'RemoveFormat',
      2 => 'Source',
    ),
    1 => 
    array (
      0 => 'Bold',
      1 => 'Italic',
      2 => 'Underline',
      3 => 'Strike',
      4 => 'Subscript',
      5 => 'Superscript',
    ),
    2 => 
    array (
      0 => 'Outdent',
      1 => 'Indent',
      2 => 'Blockquote',
    ),
    3 => 
    array (
      0 => 'JustifyLeft',
      1 => 'JustifyCenter',
      2 => 'JustifyRight',
      3 => 'JustifyBlock',
      4 => '-',
      5 => 'BidiLtr',
      6 => 'BidiRtl',
    ),
    4 => 
    array (
      0 => 'TextColor',
      1 => 'BGColor',
      2 => 'FontSize',
    ),
    5 => 
    array (
      0 => 'OrderedList',
      1 => 'UnorderedList',
    ),
    6 => 
    array (
      0 => 'Link',
      1 => 'Unlink',
      2 => 'Anchor',
    ),
  ),
  'Main' => 
  array (
    0 => 
    array (
      0 => 'Format',
    ),
    1 => 
    array (
      0 => 'Bold',
      1 => 'Italic',
    ),
    2 => 
    array (
      0 => 'Outdent',
      1 => 'Indent',
      2 => 'Blockquote',
    ),
    3 => 
    array (
      0 => 'OrderedList',
      1 => 'UnorderedList',
    ),
    4 => 
    array (
      0 => '-',
      1 => 'Link',
      2 => 'Unlink',
      3 => 'Anchor',
      4 => '-',
      5 => 'Table',
    ),
    5 => 
    array (
      0 => 'FitWindow',
      1 => 'Source',
    ),
  ),
  'Sidebar' => 
  array (
    0 => 
    array (
      0 => 'Maximize',
      1 => 'RemoveFormat',
      2 => 'Source',
    ),
    1 => 
    array (
      0 => 'Bold',
      1 => 'Italic',
      2 => 'Underline',
      3 => 'Strike',
      4 => 'Subscript',
      5 => 'Superscript',
    ),
    2 => 
    array (
      0 => 'Outdent',
      1 => 'Indent',
      2 => 'Blockquote',
    ),
    3 => 
    array (
      0 => 'JustifyLeft',
      1 => 'JustifyCenter',
      2 => 'JustifyRight',
      3 => 'JustifyBlock',
      4 => '-',
      5 => 'BidiLtr',
      6 => 'BidiRtl',
    ),
    4 => 
    array (
      0 => 'TextColor',
      1 => 'BGColor',
      2 => 'FontSize',
    ),
    5 => 
    array (
      0 => 'OrderedList',
      1 => 'UnorderedList',
    ),
    6 => 
    array (
      0 => 'Link',
      1 => 'Unlink',
      2 => 'Anchor',
    ),
  ),
  'Media' => 
  array (
    0 => 
    array (
      0 => 'Bold',
      1 => 'Italic',
    ),
    1 => 
    array (
      0 => 'Outdent',
      1 => 'Indent',
      2 => 'Blockquote',
    ),
    2 => 
    array (
      0 => 'Link',
      1 => 'Unlink',
      2 => 'Anchor',
    ),
    3 => 
    array (
      0 => 'Source',
    ),
  ),
),
  'app_a_search_service_class' => 'aMysqlSearch',
  'app_a_page_cache_enabled' => false,
  'app_a_cache_default_class' => 'aMysqlCache',
  'app_a_search_hard_limit' => 500,
  'app_a_fasthydrate' => true,
  'app_a_routes_register' => false,
  'app_a_default_on' => true,
  'app_a_pretty_english_dates' => true,
  'app_a_credit' => false,
  'app_a_pager_nb_links' => 5,
  'app_a_persistent_global_toolbar' => false,
  'app_a_global_button_order' => array (
  0 => 'blog',
  1 => 'events',
  2 => 'media',
  3 => 'categories',
  4 => 'tags',
  5 => 'users',
  6 => 'reorganize',
),
  'app_a_i18n_switch' => true,
  'app_a_i18n_languages' => array (
  0 => 'fr',
  1 => 'en',
),
  'app_a_manage_candidate_group' => 'editor',
  'app_a_manage_sufficient_group' => 'admin',
  'app_a_edit_candidate_group' => 'editor',
  'app_a_edit_sufficient_group' => 'admin',
  'app_a_view_locked_sufficient_credentials' => 'view_locked',
  'app_a_use_bundled_layout' => false,
  'app_a_title_prefix' => 'Ni !|¡ ',
  'app_a_title_suffix' => '',
  'app_a_templates' => array (
  'a' => 
  array (
    'default' => 'Default Page',
    'home' => 'Home Page',
  ),
  'aMedia' => 
  array (
    'default' => 'Media',
  ),
  'aBlog' => 
  array (
    'default' => 'Blog',
  ),
  'aEvent' => 
  array (
    'default' => 'Events',
  ),
  'aPeople' => 
  array (
    'default' => 'People',
  ),
),
  'app_a_standard_area_slots' => array (
  0 => 'aRichText',
  1 => 'aInsetImage',
  2 => 'aVideo',
  3 => 'aSlideshow',
  4 => 'aAudio',
  5 => 'aButton',
  6 => 'aBlog',
  7 => 'aEvent',
  8 => 'aRawHTML',
),
  'app_a_standard_area_extra_slot_options' => array (
  'aPeople' => 
  array (
    'itemTemplate' => 'headshot',
  ),
),
  'app_a_standard_area_force_slot_options' => array (
  'aPeople' => 
  array (
    'slideshowOptions' => 
    array (
      'width' => 200,
      'flexHeight' => true,
    ),
  ),
),
  'app_a_slot_types' => array (
  'aBlog' => 'Blog Posts',
  'aEvent' => 'Events',
  'aInsetImage' => 'Inset Image',
  'aInsetArea' => 'Inset Area',
  'aBlogSlideshow' => 'Blog Slideshow',
  'aMap' => 'Map',
  'aAnchorTitle' => 'Anchored Title',
  'aPeople' => 'People',
),
  'app_a_slot_variants' => array (
  'aSlideshow' => 
  array (
    'normal' => 
    array (
      'label' => 'Normal',
      'options' => 
      array (
        'arrows' => true,
      ),
    ),
    'autoplay' => 
    array (
      'label' => 'Autoplay',
      'options' => 
      array (
        'interval' => 4,
        'arrows' => false,
      ),
    ),
  ),
  'aInsetArea' => 
  array (
    'topLeft' => 
    array (
      'label' => 'Left Aligned',
      'options' => 
      array (
        'insetTemplate' => 'topLeft',
      ),
    ),
    'topRight' => 
    array (
      'label' => 'Right Aligned',
      'options' => 
      array (
        'insetTemplate' => 'topRight',
      ),
    ),
  ),
  'aInsetImage' => 
  array (
    'topLeft' => 
    array (
      'label' => 'Left Aligned',
      'options' => 
      array (
        'insetTemplate' => 'topLeft',
      ),
    ),
    'topRight' => 
    array (
      'label' => 'Right Aligned',
      'options' => 
      array (
        'insetTemplate' => 'topRight',
      ),
    ),
  ),
),
  'app_a_addslot_button_style' => 'big',
  'app_a_history_button_style' => 'no-label big',
  'app_a_delete_button_style' => 'no-label',
  'app_a_asset_group' => 'global',
  'app_a_use_bundled_stylesheets' => array (
  'reset' => '/apostrophePlugin/css/a-reset.less',
  'admin' => '/apostrophePlugin/css/a-admin.less',
  'forms' => '/apostrophePlugin/css/a-forms.less',
  'components' => '/apostrophePlugin/css/a-components.less',
  'engines' => '/apostrophePlugin/css/a-engines.less',
  'area-slots' => '/apostrophePlugin/css/a-area-slots.less',
  'buttons' => '/apostrophePlugin/css/a-buttons.less',
  'colors' => '/apostrophePlugin/css/a-colors.less',
  'utility' => '/apostrophePlugin/css/a-utility.less',
),
  'app_a_feed_hide_identical_description' => true,
  'app_a_js_debug' => true,
  'app_aAdmin_web_dir' => '/apostrophePlugin',
  'app_aMedia_client_apikey' => 'niDummy',
  'app_aMedia_apikeys' => array (
  0 => 'niDummy',
),
  'app_aMedia_apipublic' => false,
  'app_aMedia_admin_credential' => 'media_admin',
  'app_aMedia_upload_credential' => 'media_upload',
  'app_aMedia_use_bundled_layout' => false,
  'app_aMedia_embed_codes' => true,
  'app_aEvents_display_calendar' => true,
  'app_aBlog_templates' => array (
  'singleColumnTemplate' => 
  array (
    'name' => 'Single Column',
    'areas' => 
    array (
      0 => 'blog-body',
    ),
  ),
),
  'app_aBlog_link_author' => true,
  'app_afeedback' => NULL,
  'app_aToolkit_indexes' => array (
  0 => 'aPage',
  1 => 'aMediaItem',
),
  'app_sfSyncContent_content' => array (
  0 => 'web/uploads',
  1 => 'data/a_writable',
),
  'app_aimageconverter_path' => '/opt/local/bin',
));
