<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/03/06 17:50:21

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=ni;host=localhost',
  'username' => 'ni',
  'password' => 'ni ni sql',
  'encoding' => 'utf8',
  'attributes' => 
  array (
    'DEFAULT_TABLE_TYPE' => 'INNODB',
    'DEFAULT_TABLE_CHARSET' => 'utf8',
    'DEFAULT_TABLE_COLLATE' => 'utf8_general_ci',
  ),
  'name' => 'doctrine',
)),);
