<?php

/**
 * aPersonToACategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aPersonToACategoryTable extends PluginaPersonToACategoryTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aPersonToACategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aPersonToACategory');
    }
}