<?php

/**
 * aPersonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aPersonTable extends PluginaPersonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object aPersonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('aPerson');
    }
}