<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class aPage extends PluginaPage
{
  public function getSlugTrimmed ()
  {
    return substr(strrchr($this->slug, "/"), 1);
  }

}