<?php

/**
 * aEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    asandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class aEvent extends PluginaEvent
{

  public function getRealTitle()
  {
    return $this->_get('title');
  }

  public function getFeedRealTitle()
  {
    return html_entity_decode($this->getRealTitle(), ENT_COMPAT, 'UTF-8');
  }

}
